"""Add push_subscription field to User

Revision ID: 05faea793afd
Revises: 1e541b9ced95
Create Date: 2025-11-24 19:47:17.633743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05faea793afd'
down_revision = '1e541b9ced95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    # ### end Alembic commands ###
