"""Add Employee model

Revision ID: 1e541b9ced95
Revises: c3fa6905edb6
Create Date: 2025-11-24 12:28:09.427200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e541b9ced95'
down_revision = 'c3fa6905edb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['parent'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['parent'], ['tree.id'], name='tree_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('employee')
    # ### end Alembic commands ###
