"""add file attachment to posts

Revision ID: 4b617e1dbcc7
Revises: f8235cdbc1bb
Create Date: 2025-11-29 12:04:19.965133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b617e1dbcc7'
down_revision = 'f8235cdbc1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_mimetype', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('file_mimetype')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
