"""add file attachment to messages

Revision ID: f8235cdbc1bb
Revises: 05faea793afd
Create Date: 2025-11-29 11:47:35.887160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8235cdbc1bb'
down_revision = '05faea793afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_mimetype', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_mimetype')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
